//Import area       

import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import { Inter } from 'next/font/google'
import Header from '@/component/layouts/Header'
import RightAside from '@/component/layouts/RightAside'
import LeftAside from '@/component/layouts/LeftAside'
import Footer from '@/component/layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//Defenation area
export default function RootLayout({ children }) {  // function start
  //fucntion return statement

  return (
    <div className='container  p-0'>
      <Header />
      <main>
        <div className='row  m-0'>
          <RightAside />
          {children}
          <LeftAside />
        </div>
      </main>
      <Footer />

    </div>
  )
}   //Function end
//Export area